#  Can one block of except statements handle multiple exception? 
"""
Yes, one except block can handle multiple exceptions by listing 
them as a tuple.

syntax :

try:
    # code 

except (ValueError, TypeError):
    # handle both ValueError and TypeError

"""